"""
TTYBOTRON
=========
A TTY Tubotron.

.. todo::
 * Command line args for:
   * Port to listen on
   * Filtering by IP, chip, core, etc.
"""

import socket, struct, sys, threading

def make_socket( port ):
    """Make an appropriate socket for receiving SDP packets.

    :param port: Port to listen on.
    :returns: An open socket.
    """
    # Instantiate the socket, set non-blocking
    _socket = socket.socket( socket.AF_INET, socket.SOCK_DGRAM )
    _socket.setblocking( 0 )
    _socket.bind( ( "", port ) )
    return _socket


class SDPPrintPacket( object ):
    """An SDP Packet as generated by the spin1_printf or similar function.

    :param data: An array of bytes as received from a socket.
    :type data: array
    """
    def __init__( self, data ):
        # Process the data and save
        header = data[2:2+8]
        data = data[2+8+4:]

        # Unpack the header
        (flags, iptag, dest_port, srce_port, dest_addr, srce_addr) = (
            struct.unpack( "!4B 2H", header ) )
   
        (chip_x, chip_y) = (
            struct.unpack( "2B", struct.pack( "H", srce_addr ) ) )
  
        core = srce_port & 0x1f

        # Save all this data
        self.flags = flags
        self.iptag = iptag
        self.dest_port = dest_port
        self.srce_port = srce_port
        self.dest_addr = dest_addr
        self.srce_addr = srce_addr

        self.chip_x = chip_x
        self.chip_y = chip_y
        self.core = core

class SDPPrintReceiver( threading.Thread ):
    """Creates a thread which keeps trying to receive SDP messages.  When a 
    message is received the provided callback is called with the message.

    :param socket: Socket to check.
    :param callback: Function to call when a packet is received.
    """
    def __init__( self, socket, callback ):
        # Save the socket and callback
        self._socket = socket
        self._callback = callback

    def run( self ):
        # Run as long as we can...
        while True:
            # Try to receive a packet
            try:
                data = self._socket.recv()

                # Call the callback with the packet
                packet = SDPPrintPacket( data )
                self._callback( packet )
            except IOError: # There was nothing to get
                pass

def ttybotron( port = 17892 ):
    """Continue to poll an incoming socket on the appropriate port and print
    out a formatted string of the machine, chip, core and message."""
    # Set up the socket
    sock = socket.socket( socket.AF_INET, socket.SOCK_DGRAM )
    sock.bind( ( "", port ) )

    try:
        while True:
            # Grab the stuff from the socket
            (data, addr) = sock.recvfrom( 1024 ) # Socket size is 1024 bytes

            # Unpack the data
            header = data[2:2+8]
            data = data[2+8+4:]
    
            # Unpack the header
            (flags, iptag, dest_port, srce_port, dest_addr, srce_addr) = (
                struct.unpack( "!4B 2H", header ) )
    
            (chip_x, chip_y) = (
                struct.unpack( "2B", struct.pack( "H", srce_addr ) ) )
    
            core = srce_port & 0x1f
    
            # Reverse look up the DNS for the incoming SpiNNaker board
            # hn = socket.gethostbyaddr( addr )

            # Now output any desired information
            sys.stdout.write( "(%s, %2d, %2d, %2d) %s" % (
                                "", core, chip_x, chip_y, data
                            )
            )
            sys.stdout.flush()
    except KeyboardInterrupt:
        pass
    finally:
        sys.stdout.flush()
        sock.close()

if __name__ == "__main__":
    ttybotron( )
